version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pet-manage-db
    environment:
      POSTGRES_DB: petdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pet-manage-volume:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pet-manage-volume:
    name: pet-manage-volume
