version: "3.8"

services:
  pet-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - PORT=8080
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    restart: unless-stopped
